name: Run Cron Job Every 5 Minutes

on:
  schedule:
    # Runs every 5 minutes
    - cron: '*/5 * * * *'

jobs:
  cron-job:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Next PGP API to Lock Inactive Vaults
        run: |
          curl -X POST https://nextpgp.vercel.app/api/vault/lock-inactive-vaults \
            -H "Authorization: Bearer $NEXT_VAULT_SECRET"